name: NerunyaCore
version: ${project.version}
main: nagatuki.nerunyacore.NerunyaCore
api-version: 1.13

commands:
  nerunyacore:
    description: Main command for nerunyacore.
    usage: /<command> (Startup error)
    aliases: [nc]
  motd:
    description: motd.
    usage: /<command> (Startup error)